language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
install:
  - npm install
  - bower update
  - mv bower_components/ app/
script:
<<<<<<< HEAD
  - gulp serve
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
=======
  - gulp wct:local
>>>>>>> d28565c3a531f6d279de5a719580e838e48d811c
